spring.application.name=safework-backend
spring.profiles.active=${APP_PROFILE:dev}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.naming.physical-strategy=com.nexorape.safework.service.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
spring.flyway.enabled=false
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.time-zone=UTC
spring.jackson.datatype.datetime.write-dates-as-timestamps=false
authorization.jwt.secret=${JWT_SECRET}
authorization.jwt.expiration.days=${JWT_EXPIRATION:7}
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate=INFO
server.error.include-message=never
server.error.include-stacktrace=never
server.address=${SERVER_ADDRESS:127.0.0.1}
server.port=${SERVER_PORT:8080}


spring.jackson.mapper.allow-coercion-of-scalars=false
spring.jackson.deserialization.accept-float-as-int=false
